### ISSUE TITLE
monaco-editor error

### ISSUE THREAD

**Issue by nrydevopswatch** [grommet/grommet-site#142]
When I run:
```
npm run start
```
I'm getting the following errors in the terminal:
```
ERROR in ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css (./node_modules/css-loader/dist/cjs.js!./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css) 4:36-60
 @ ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css
 @ ./node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codiconLabel.js
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestWidget.js
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestController.js
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js
 @ ./node_modules/react-monaco-editor/lib/editor.js
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./src/screens/Play.js
 @ ./src/components/Content.js
 @ ./src/App.js
 @ ./src/index.js
```
```
ℹ ｢wdm｣: Failed to compile.
```

**Comment by ShimiSun** [comment]
Hi buddy, thanks for filing an issue.
I used to see this error as well, but after cleaning up the project I don't see it anymore.
Can you please try to clean up all cached files to see if it reproduces, and let me know how it goes? 
`rm -rf node_modules`
`rm -rf package-lock.json`
`rm -rf yarn.lock`
`yarn cache clean`

**Comment by nrydevopswatch** [comment]
@ShimiSun Thank you for the reply and help with this. I just tried to follow the steps you provided to clean out the npm modules and cache, but I still got the same error. I'm running this on a Google Cloud Shell which is "ephemeral and no system-wide change will persist beyond session end" and it seemed that they have a slightly older version of Node LTS installed (6.4.1) so I upgrade to the latest LTS (6.13.4) version. However that is still giving me the following errors:

```
nrydevops@cloudshell:~/grommet-site (nrydevops)$ npm run start

> grommet-site@0.1.0 start /home/nrydevops/grommet-site
> cross-env NODE_ENV=development webpack-dev-server --mode development --open

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/gotoSymbol/goToCommands'
Require stack:
- /home/nrydevops/grommet-site/node_modules/monaco-editor-webpack-plugin/out/index.js
- /home/nrydevops/grommet-site/webpack.config.js
- /home/nrydevops/grommet-site/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/nrydevops/grommet-site/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at resolveMonacoPath (/home/nrydevops/grommet-site/node_modules/monaco-editor-webpack-plugin/out/index.js:26:20)
    at /home/nrydevops/grommet-site/node_modules/monaco-editor-webpack-plugin/out/index.js:161:63
    at Array.map (<anonymous>)
    at createLoaderRules (/home/nrydevops/grommet-site/node_modules/monaco-editor-webpack-plugin/out/index.js:161:43)
    at MonacoEditorWebpackPlugin.apply (/home/nrydevops/grommet-site/node_modules/monaco-editor-webpack-plugin/out/index.js:80:23)
    at webpack (/home/nrydevops/grommet-site/node_modules/webpack/lib/webpack.js:51:13)
    at startDevServer (/home/nrydevops/grommet-site/node_modules/webpack-dev-server/bin/webpack-dev-server.js:94:16)
    at /home/nrydevops/grommet-site/node_modules/webpack-dev-server/bin/webpack-dev-server.js:166:3
    at /home/nrydevops/grommet-site/node_modules/webpack-dev-server/lib/utils/processOptions.js:33:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grommet-site@0.1.0 start: `cross-env NODE_ENV=development webpack-dev-server --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grommet-site@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nrydevops/.npm/_logs/2019-12-30T15_12_36_117Z-debug.log
```

I did try it with both ```yarn install``` as well as ```npm install``` and cleaning the npm_modules and cache each time following your instructions.

**Comment by karatechops** [comment]
Hi @nrydevopswatch - I recently locked in the version of Monaco / Monaco webpack plugin, can you try @ShimiSun 's steps again and let us know if it is still failing?

```bash
rm -rf node_modules && rm package-lock.json && rm yarn.lock && yarn cache clean && yarn
```

**Comment by nrydevopswatch** [comment]
Hello @karatechops 

I just cloned a fresh copy of the project and then followed @ShimiSun 's steps above. I am testing this on a Google Cloud Shell. Actually the first time I did `npm install` after running the suggested fix, and then `npm run start` it failed to compile but then when I ran the following suggested fix again:

`rm -rf node_modules && rm -rf package-lock.json && rm -rf yarn.lock && yarn cache clean && yarn`

It now works and I'm able to launch the website on `port 8567`

In the Google Cloud Shell it has the following installed by default:
npm version 6.4.1
node version 10.14.2

It does get the following warning but does not seem to effect anything:
```
WARNING in ./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
    Module not found: Error: Can't resolve '@microsoft/typescript-etw' in '/home/nrydevops/grommet-site/node_modules/monaco-editor/esm/vs/language/typescript/lib'
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/tsWorker.js
     @ ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js
ℹ ｢wdm｣: Compiled with warnings.
```
