### ISSUE TITLE
Accordion, Drop broken on storybook

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet-site#72]
When I click on Accordion > Rich I'm getting this error in [Storybook](https://storybook.grommet.io):

`Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:480
    at t (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:583)
    at af (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:41529)
    at r (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:51477)
    at B (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:52750)
    at https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:54726
    at Q (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:55966)
    at Ag (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:63993)
    at lh (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:78923)
    at mh (https://storybook.grommet.io/vendors~main.b3a5bbf6ad3aa16002dc.bundle.js:48:79288)`

Similar issue for Drop > All not stretch

**Comment by ShimiSun** [comment]
@markjackson02 if this is a storybook issue it should go on grommet core. thanks for letting us know!

**Comment by markjackson02** [comment]
@ShimiSun ok I created it there: https://github.com/grommet/grommet/issues/2710 Thanks

**Comment by ShimiSun** [comment]
@markjackson02 we appreciate your cooperation, thanks!
